const PHYSICS_ACCEL=0.01;
const PHYSICS_FRICTION=0.9;

const PHYSICS_MAX_V_X=10;
const PHYSICS_MAX_V_Y=1;

const PHYSICS_OBS_MAX_V=20;
const PHYSICS_OBS_ACCEL=0.02;

const DRIFT_TO_Y=100;

const OBSTACLE_SPEED_TICK=0.001;
const OBSTACLE_SPEED_START=2;
const OBSTACLE_SPAWN=70;

const TILE_WIDTH=20;
const TILE_HEIGHT=40;

const STAGE_WIDTH=540;
const STAGE_HEIGHT=540;

var TILES_ACROSS=STAGE_WIDTH/TILE_WIDTH;
var TILES_DOWN=STAGE_HEIGHT/TILE_HEIGHT;